import Anthropic from '@anthropic-ai/sdk'
import { execSync } from 'child_process'

const {
  ANTHROPIC_API_KEY,
  POST_IF_EMPTY = 'true',
  MODE = 'diff',
  GITHUB_TOKEN,
  PR_NUMBER,
  PR_BODY = '',
  PR_TITLE = '',
  PR_URL = '',
  PR_AUTHOR = '',
  BASE_REF,
  HEAD_REF,
  REPO,
  SLACK_WEBHOOK_URL = '',
} = process.env

if (!ANTHROPIC_API_KEY) {
  console.error('Error: ANTHROPIC_API_KEY is required.')
  process.exit(1)
}

if (!PR_NUMBER || !REPO) {
  console.error('Error: This action must run on a pull_request event.')
  process.exit(1)
}

// Skip if post-if-empty is true and PR already has a description
if (POST_IF_EMPTY === 'true' && PR_BODY && PR_BODY.trim().length > 0) {
  console.log('PR already has a description. Skipping.')
  process.exit(0)
}

function run(cmd) {
  try {
    return execSync(cmd, { encoding: 'utf-8', stdio: ['pipe', 'pipe', 'pipe'] }).trim()
  } catch {
    return ''
  }
}

function getCommits() {
  const log = run(`git log origin/${BASE_REF}..HEAD --oneline --no-merges`)
  if (log) return log
  return run('git log -20 --oneline --no-merges')
}

function getDiff() {
  const diff = run(`git diff origin/${BASE_REF}...HEAD -- . ":(exclude)package-lock.json" ":(exclude)yarn.lock" ":(exclude)pnpm-lock.yaml"`)
  return diff.slice(0, 6000)
}

function getStatus() {
  return run('git status --short')
}

function buildPrompt(commits, diff, branch) {
  const sections = []
  if (branch) sections.push(`Branch: ${branch}`)
  if (commits) sections.push(`Commits:\n${commits}`)
  if (diff) sections.push(`Diff summary:\n${diff}`)

  const context = sections.join('\n\n')

  return `You are a senior engineer writing a pull request description. Based on the git context below, produce clean, useful PR copy.

${context}

Respond with exactly this structure — no extra commentary:

## PR Title
[conventional commit style, max 72 chars]

## PR Description
**What changed:** [2-4 sentences]
**Why:** [1-2 sentences on motivation]
**How to test:** [numbered steps]

## Changelog Entry
[ready-to-paste changelog line in Keep a Changelog format]

## Reviewer Notes
[what reviewers should focus on, what to skip, any gotchas]

## Testing Checklist
- [ ] [item]
- [ ] [item]
[add as many as relevant]`
}

function formatComment(output) {
  return `## PRetty generated PR description

> Generated by [PRetty](https://github.com/alexandrakay/pretty-pr). Copy what's useful, ignore the rest.

${output}

---
<sub>Re-run by editing the PR description or closing and reopening the PR.</sub>`
}

function extractOneLiner(output) {
  const match = output.match(/\*\*What changed:\*\*\s*([^\n]+)/)
  if (match) return match[1].trim()
  const firstLine = output.split('\n').find((l) => l.trim() && !l.startsWith('#'))
  return firstLine?.trim() || 'A new PR was opened.'
}

async function postSlack(summary) {
  const text = `*<${PR_URL}|${PR_TITLE || 'New PR'}>* by \`${PR_AUTHOR}\`\n${summary}`
  const res = await fetch(SLACK_WEBHOOK_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ text }),
  })
  if (!res.ok) {
    const body = await res.text()
    console.error(`Slack post failed: ${res.status} ${body}`)
  }
}

async function postComment(body) {
  const [owner, repoName] = REPO.split('/')
  const url = `https://api.github.com/repos/${owner}/${repoName}/issues/${PR_NUMBER}/comments`

  const res = await fetch(url, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${GITHUB_TOKEN}`,
      'Content-Type': 'application/json',
      Accept: 'application/vnd.github+json',
    },
    body: JSON.stringify({ body }),
  })

  if (!res.ok) {
    const text = await res.text()
    throw new Error(`Failed to post comment: ${res.status} ${text}`)
  }

  const data = await res.json()
  return data.html_url
}

const commits = getCommits()
if (!commits) {
  console.log('No commits found. Skipping.')
  process.exit(0)
}

const diff = MODE !== 'commits' ? getDiff() : null
const status = MODE === 'full' ? getStatus() : null
const branch = HEAD_REF || ''

console.log(`Generating PR description (mode: ${MODE})...`)

const client = new Anthropic({ apiKey: ANTHROPIC_API_KEY })
const prompt = buildPrompt(commits, diff, branch)

const message = await client.messages.create({
  model: 'claude-opus-4-7',
  max_tokens: 1024,
  system: 'You write precise, honest pull request descriptions for software engineers. No fluff.',
  messages: [{ role: 'user', content: prompt }],
})

const output = message.content[0].text
const commentBody = formatComment(output)
const commentUrl = await postComment(commentBody)

console.log(`Posted: ${commentUrl}`)

if (SLACK_WEBHOOK_URL) {
  const summary = extractOneLiner(output)
  await postSlack(summary)
  console.log('Slack summary posted.')
}
